### ISSUE TITLE
Page links meta data

### ISSUE THREAD

**Issue by woodRock** [woodRock/woodrock.github.io#29]
## Goal 
Include metadata for the main pages for the website in the search engine results. 

## Tasklist 
- [ ] research how to do this
- [ ] provide metadata for each page 
- [ ] verify search results have changed

## Success Criteria
When the user searches for the website on a search engine, the metadata for the important pages is displayed in the results.

**Comment by woodRock** [comment]
[Here](https://duckduckgo.com/?q=facebook+&t=newext&atb=v242-1&ia=web) is an example of the search engine results that we would like the website to have.

![Screenshot from 2020-11-17 16-48-02](https://user-images.githubusercontent.com/18411037/99344501-205d0e00-28f5-11eb-8d64-692964b88e22.png)

**Comment by woodRock** [comment]
I have written a [sitemap](https://woodrock.tk/sitemap.xml) for the website using xml. This can be registered on using the Google Search Console tool.
